---
abstract: 'EPP <=> SRS XML proxy server'
author:
  - 'Catalyst SRS Team <team-srs@catalyst.net.nz>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SRS-EPP-Proxy
no_index:
  directory:
    - inc
    - t
requires:
  Crypt::Password: 0
  Event: 0
  Log::Dispatch: 0
  Module::Pluggable: 0
  Moose: 0.54
  MooseX::Daemonize: 0
  MooseX::Getopt: 0
  MooseX::Log::Log4perl: 0
  MooseX::Method::Signatures: 0
  MooseX::SimpleConfig: 0
  MooseX::Singleton: 0
  Net::SSLeay::OO: 0
  PRANG: 0.09
  XML::EPP: 0.03
  XML::SRS: 0.03
  perl: 5.008005
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: 0.1
