---
abstract: 'EPP <=> SRS XML proxy server'
author:
  - 'Catalyst SRS Team <team-srs@catalyst.net.nz>'
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SRS-EPP-Proxy
no_index:
  directory:
    - inc
    - t
requires:
  Crypt::Password: 0
  Event: 0
  Log::Dispatch: 0
  Module::Pluggable: 0
  Moose: 0.54
  MooseX::Daemonize: 0
  MooseX::Getopt: 0
  MooseX::Log::Log4perl: 0
  MooseX::Method::Signatures: 0
  MooseX::SimpleConfig: 0
  MooseX::Singleton: 0
  Net::SSLeay::OO: 0
  PRANG: 0.11
  XML::Assert: 0.02
  XML::EPP: 0.05
  XML::SRS: 0.06
  perl: 5.008005
version: 0.21
